import { Josefin_Sans } from "next/font/google";
import "./globals.css";
// import { HeroUIProvider } from "@heroui/react";

import Navbar from "@/components/Navbar";
import Banner from "@/components/Banner";
import Footer from "@/components/Footer";

const josefin = Josefin_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${josefin.className} h-full antialiased`}
    >
      <body
        className="min-h-full flex flex-col"
        suppressHydrationWarning
      >

        <Navbar />
        <Banner />
        
        {children}
        
        <Footer />
        
  
      </body>
    </html>
  );
}
